# Generated by Django 4.1.4 on 2022-12-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='name'),
        ),
    ]
