# Generated by Django 4.1.4 on 2022-12-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbsmanagement', '0002_alter_info_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='id',
        ),
        migrations.AddField(
            model_name='info',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='number',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
