# Generated by Django 4.1.4 on 2022-12-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbsmanagement', '0003_remove_info_id_info_barcode_alter_info_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='name',
            new_name='animal',
        ),
    ]
