# Generated by Django 4.1.4 on 2022-12-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbsmanagement', '0004_rename_name_info_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='animal',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='info',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
