# Generated by Django 4.1.4 on 2022-12-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbsmanagement', '0007_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='number',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
