# Generated by Django 4.1.4 on 2022-12-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbsmanagement', '0009_alter_info_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
