# Generated by Django 4.1.4 on 2022-12-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbsmanagement', '0011_alter_info_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, upload_to='Reference/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='animal',
            field=models.CharField(default='', max_length=120, null=True, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='info',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
