# Generated by Django 4.1.4 on 2022-12-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbsmanagement', '0012_info_image_alter_info_animal_alter_info_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
