# Generated by Django 4.1.4 on 2023-01-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbsmanagement', '0015_alter_info_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, upload_to='Reference/', verbose_name='Image(Optional)'),
        ),
    ]
